/**
 * Week -> illustration map. GENERATED by scripts/extract-bulles.py's companion step; edit
 * that, not this.
 *
 * Static `require`s because React Native's bundler resolves local assets at build time — a
 * computed path (`require(\`./week-${n}.png\`)`) does not work.
 *
 * Indexed by SG (semaines de grossesse), NOT SA. The source sheet shows a blastocyst at
 * "week 1", which only exists post-conception, so the sheet is gestational age. Bulle counts
 * in SA everywhere else (§7.2), and SG = SA - 2 — feeding it SA would show every parent an
 * illustration two weeks ahead of themselves.
 */
export const WEEK_BULLES: Record<number, number> = {
  1: require('./week-01.png'),
  2: require('./week-02.png'),
  3: require('./week-03.png'),
  4: require('./week-04.png'),
  5: require('./week-05.png'),
  6: require('./week-06.png'),
  7: require('./week-07.png'),
  8: require('./week-08.png'),
  9: require('./week-09.png'),
  10: require('./week-10.png'),
  11: require('./week-11.png'),
  12: require('./week-12.png'),
  13: require('./week-13.png'),
  14: require('./week-14.png'),
  15: require('./week-15.png'),
  16: require('./week-16.png'),
  17: require('./week-17.png'),
  18: require('./week-18.png'),
  19: require('./week-19.png'),
  20: require('./week-20.png'),
  21: require('./week-21.png'),
  22: require('./week-22.png'),
  23: require('./week-23.png'),
  24: require('./week-24.png'),
  25: require('./week-25.png'),
  26: require('./week-26.png'),
  27: require('./week-27.png'),
  28: require('./week-28.png'),
  29: require('./week-29.png'),
  30: require('./week-30.png'),
  31: require('./week-31.png'),
  32: require('./week-32.png'),
  33: require('./week-33.png'),
  34: require('./week-34.png'),
  35: require('./week-35.png'),
  36: require('./week-36.png'),
  37: require('./week-37.png'),
  38: require('./week-38.png'),
  39: require('./week-39.png'),
  40: require('./week-40.png'),
};

/** Clamped lookup. Weeks outside 1..40 fall back to the nearest end of the sheet. */
export function bulleForWeekSG(weekSG: number): number {
  const clamped = Math.max(1, Math.min(40, Math.round(weekSG)));
  return WEEK_BULLES[clamped];
}
